<?php

/**
 * BaseCompanySocial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $company_id
 * @property bigint $social_id
 * @property string $value
 * @property Company $Company
 * @property Social $Social
 * 
 * @method bigint        getCompanyId()  Returns the current record's "company_id" value
 * @method bigint        getSocialId()   Returns the current record's "social_id" value
 * @method string        getValue()      Returns the current record's "value" value
 * @method Company       getCompany()    Returns the current record's "Company" value
 * @method Social        getSocial()     Returns the current record's "Social" value
 * @method CompanySocial setCompanyId()  Sets the current record's "company_id" value
 * @method CompanySocial setSocialId()   Sets the current record's "social_id" value
 * @method CompanySocial setValue()      Sets the current record's "value" value
 * @method CompanySocial setCompany()    Sets the current record's "Company" value
 * @method CompanySocial setSocial()     Sets the current record's "Social" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanySocial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_social');
        $this->hasColumn('company_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('social_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasOne('Social', array(
             'local' => 'social_id',
             'foreign' => 'id'));
    }
}