<?php

/**
 * BaseProductOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $number
 * @property date $purchase_date
 * @property bigint $agent_id
 * @property bigint $customer_id
 * @property bigint $company_id
 * @property bigint $status_order_id
 * @property Agent $Agent
 * @property OrderStatus $OrderStatus
 * 
 * @method string       getNumber()          Returns the current record's "number" value
 * @method date         getPurchaseDate()    Returns the current record's "purchase_date" value
 * @method bigint       getAgentId()         Returns the current record's "agent_id" value
 * @method bigint       getCustomerId()      Returns the current record's "customer_id" value
 * @method bigint       getCompanyId()       Returns the current record's "company_id" value
 * @method bigint       getStatusOrderId()   Returns the current record's "status_order_id" value
 * @method Agent        getAgent()           Returns the current record's "Agent" value
 * @method OrderStatus  getOrderStatus()     Returns the current record's "OrderStatus" value
 * @method ProductOrder setNumber()          Sets the current record's "number" value
 * @method ProductOrder setPurchaseDate()    Sets the current record's "purchase_date" value
 * @method ProductOrder setAgentId()         Sets the current record's "agent_id" value
 * @method ProductOrder setCustomerId()      Sets the current record's "customer_id" value
 * @method ProductOrder setCompanyId()       Sets the current record's "company_id" value
 * @method ProductOrder setStatusOrderId()   Sets the current record's "status_order_id" value
 * @method ProductOrder setAgent()           Sets the current record's "Agent" value
 * @method ProductOrder setOrderStatus()     Sets the current record's "OrderStatus" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_order');
        $this->hasColumn('number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('purchase_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('agent_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('customer_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('company_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('status_order_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));

        $this->hasOne('OrderStatus', array(
             'local' => 'status_order_id',
             'foreign' => 'id'));

        $blameable0 = new Doctrine_Template_Blameable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($blameable0);
        $this->actAs($versionable0);
        $this->actAs($softdelete0);
    }
}