<?php

/**
 * BaseConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * 
 * @method string        getName()  Returns the current record's "name" value
 * @method string        getValue() Returns the current record's "value" value
 * @method Configuration setName()  Sets the current record's "name" value
 * @method Configuration setValue() Sets the current record's "value" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuration');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}