<?php

/**
 * BaseDiscountType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $OrderDetail
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getOrderDetail() Returns the current record's "OrderDetail" collection
 * @method DiscountType        setName()        Sets the current record's "name" value
 * @method DiscountType        setOrderDetail() Sets the current record's "OrderDetail" collection
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscountType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discount_type');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OrderDetail', array(
             'local' => 'id',
             'foreign' => 'discount_type_id'));
    }
}