<?php

/**
 * BaseCompanyAgent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $company_id
 * @property bigint $agent_id
 * @property Company $Company
 * @property Agent $Agent
 * 
 * @method bigint       getCompanyId()  Returns the current record's "company_id" value
 * @method bigint       getAgentId()    Returns the current record's "agent_id" value
 * @method Company      getCompany()    Returns the current record's "Company" value
 * @method Agent        getAgent()      Returns the current record's "Agent" value
 * @method CompanyAgent setCompanyId()  Sets the current record's "company_id" value
 * @method CompanyAgent setAgentId()    Sets the current record's "agent_id" value
 * @method CompanyAgent setCompany()    Sets the current record's "Company" value
 * @method CompanyAgent setAgent()      Sets the current record's "Agent" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyAgent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_agent');
        $this->hasColumn('company_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('agent_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}