<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $contact_user
 * @property Doctrine_Collection $contact_company
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getContactUser()     Returns the current record's "contact_user" collection
 * @method Doctrine_Collection getContactCompany()  Returns the current record's "contact_company" collection
 * @method Contact             setName()            Sets the current record's "name" value
 * @method Contact             setContactUser()     Sets the current record's "contact_user" collection
 * @method Contact             setContactCompany()  Sets the current record's "contact_company" collection
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserContact as contact_user', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $this->hasMany('CompanyContact as contact_company', array(
             'local' => 'id',
             'foreign' => 'contact_id'));
    }
}