<?php

/**
 * BaseAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $route
 * @property string $city
 * @property string $province
 * @property string $region
 * @property string $country
 * @property string $postal_code
 * @property decimal $latitude
 * @property decimal $longitude
 * @property Doctrine_Collection $CompanyAddress
 * 
 * @method string              getRoute()          Returns the current record's "route" value
 * @method string              getCity()           Returns the current record's "city" value
 * @method string              getProvince()       Returns the current record's "province" value
 * @method string              getRegion()         Returns the current record's "region" value
 * @method string              getCountry()        Returns the current record's "country" value
 * @method string              getPostalCode()     Returns the current record's "postal_code" value
 * @method decimal             getLatitude()       Returns the current record's "latitude" value
 * @method decimal             getLongitude()      Returns the current record's "longitude" value
 * @method Doctrine_Collection getCompanyAddress() Returns the current record's "CompanyAddress" collection
 * @method Address             setRoute()          Sets the current record's "route" value
 * @method Address             setCity()           Sets the current record's "city" value
 * @method Address             setProvince()       Sets the current record's "province" value
 * @method Address             setRegion()         Sets the current record's "region" value
 * @method Address             setCountry()        Sets the current record's "country" value
 * @method Address             setPostalCode()     Sets the current record's "postal_code" value
 * @method Address             setLatitude()       Sets the current record's "latitude" value
 * @method Address             setLongitude()      Sets the current record's "longitude" value
 * @method Address             setCompanyAddress() Sets the current record's "CompanyAddress" collection
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address');
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('province', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('region', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('country', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('postal_code', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('latitude', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 18,
             ));
        $this->hasColumn('longitude', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Company as CompanyAddress', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $geographical0 = new Doctrine_Template_Geographical(array(
             ));
        $this->actAs($geographical0);
    }
}