<?php

/**
 * BaseOrderDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $order_id
 * @property bigint $product_id
 * @property integer $quantity
 * @property decimal $discount
 * @property bigint $company_id
 * @property bigint $agent_id
 * @property bigint $discount_type_id
 * @property string $note
 * @property Company $Company
 * @property Agent $Agent
 * @property DiscountType $DiscountType
 * 
 * @method bigint       getOrderId()          Returns the current record's "order_id" value
 * @method bigint       getProductId()        Returns the current record's "product_id" value
 * @method integer      getQuantity()         Returns the current record's "quantity" value
 * @method decimal      getDiscount()         Returns the current record's "discount" value
 * @method bigint       getCompanyId()        Returns the current record's "company_id" value
 * @method bigint       getAgentId()          Returns the current record's "agent_id" value
 * @method bigint       getDiscountTypeId()   Returns the current record's "discount_type_id" value
 * @method string       getNote()             Returns the current record's "note" value
 * @method Company      getCompany()          Returns the current record's "Company" value
 * @method Agent        getAgent()            Returns the current record's "Agent" value
 * @method DiscountType getDiscountType()     Returns the current record's "DiscountType" value
 * @method OrderDetail  setOrderId()          Sets the current record's "order_id" value
 * @method OrderDetail  setProductId()        Sets the current record's "product_id" value
 * @method OrderDetail  setQuantity()         Sets the current record's "quantity" value
 * @method OrderDetail  setDiscount()         Sets the current record's "discount" value
 * @method OrderDetail  setCompanyId()        Sets the current record's "company_id" value
 * @method OrderDetail  setAgentId()          Sets the current record's "agent_id" value
 * @method OrderDetail  setDiscountTypeId()   Sets the current record's "discount_type_id" value
 * @method OrderDetail  setNote()             Sets the current record's "note" value
 * @method OrderDetail  setCompany()          Sets the current record's "Company" value
 * @method OrderDetail  setAgent()            Sets the current record's "Agent" value
 * @method OrderDetail  setDiscountType()     Sets the current record's "DiscountType" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_detail');
        $this->hasColumn('order_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('discount', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('company_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('agent_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('discount_type_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasOne('Agent', array(
             'local' => 'agent_id',
             'foreign' => 'id'));

        $this->hasOne('DiscountType', array(
             'local' => 'discount_type_id',
             'foreign' => 'id'));

        $blameable0 = new Doctrine_Template_Blameable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($blameable0);
        $this->actAs($versionable0);
        $this->actAs($softdelete0);
    }
}