<?php

/**
 * BaseAgent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $surname
 * @property string $vat
 * @property string $cf
 * @property string $iban
 * @property bigint $sf_guard_user_id
 * @property bigint $address_id
 * @property Address $Address
 * @property sfGuardUser $User
 * @property Doctrine_Collection $CompanyAgent
 * @property Doctrine_Collection $agent_order
 * @property Doctrine_Collection $OrderDetail
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getSurname()          Returns the current record's "surname" value
 * @method string              getVat()              Returns the current record's "vat" value
 * @method string              getCf()               Returns the current record's "cf" value
 * @method string              getIban()             Returns the current record's "iban" value
 * @method bigint              getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method bigint              getAddressId()        Returns the current record's "address_id" value
 * @method Address             getAddress()          Returns the current record's "Address" value
 * @method sfGuardUser         getUser()             Returns the current record's "User" value
 * @method Doctrine_Collection getCompanyAgent()     Returns the current record's "CompanyAgent" collection
 * @method Doctrine_Collection getAgentOrder()       Returns the current record's "agent_order" collection
 * @method Doctrine_Collection getOrderDetail()      Returns the current record's "OrderDetail" collection
 * @method Agent               setName()             Sets the current record's "name" value
 * @method Agent               setSurname()          Sets the current record's "surname" value
 * @method Agent               setVat()              Sets the current record's "vat" value
 * @method Agent               setCf()               Sets the current record's "cf" value
 * @method Agent               setIban()             Sets the current record's "iban" value
 * @method Agent               setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Agent               setAddressId()        Sets the current record's "address_id" value
 * @method Agent               setAddress()          Sets the current record's "Address" value
 * @method Agent               setUser()             Sets the current record's "User" value
 * @method Agent               setCompanyAgent()     Sets the current record's "CompanyAgent" collection
 * @method Agent               setAgentOrder()       Sets the current record's "agent_order" collection
 * @method Agent               setOrderDetail()      Sets the current record's "OrderDetail" collection
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agent');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('surname', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('vat', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('cf', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('iban', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('sf_guard_user_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('address_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasMany('CompanyAgent', array(
             'local' => 'id',
             'foreign' => 'agent_id'));

        $this->hasMany('ProductOrder as agent_order', array(
             'local' => 'id',
             'foreign' => 'agent_id'));

        $this->hasMany('OrderDetail', array(
             'local' => 'id',
             'foreign' => 'agent_id'));
    }
}