<?php

/**
 * BaseCompanyContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $company_id
 * @property bigint $contact_id
 * @property string $value
 * @property Company $Company
 * @property Contact $Contact
 * 
 * @method bigint         getCompanyId()  Returns the current record's "company_id" value
 * @method bigint         getContactId()  Returns the current record's "contact_id" value
 * @method string         getValue()      Returns the current record's "value" value
 * @method Company        getCompany()    Returns the current record's "Company" value
 * @method Contact        getContact()    Returns the current record's "Contact" value
 * @method CompanyContact setCompanyId()  Sets the current record's "company_id" value
 * @method CompanyContact setContactId()  Sets the current record's "contact_id" value
 * @method CompanyContact setValue()      Sets the current record's "value" value
 * @method CompanyContact setCompany()    Sets the current record's "Company" value
 * @method CompanyContact setContact()    Sets the current record's "Contact" value
 * 
 * @package    tradeagent
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_contact');
        $this->hasColumn('company_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('contact_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id'));
    }
}