<?php

/**
 * AgentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agent');
    }
}