<?php

/**
 * CompanySocialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanySocialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanySocialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanySocial');
    }
}