<?php

/**
 * CompanyContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyContact');
    }
}