<?php

/**
 * CompanyAgentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyAgentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyAgentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyAgent');
    }
}