<?php

/**
 * DiscountTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscountTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscountTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscountType');
    }
}