<?php

/**
 * OrderStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderStatus');
    }
}