<?php

/**
 * ProductOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductOrder');
    }
}