<?php

/**
 * SocialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Social');
    }
}