<?php

/**
 * UserSocialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSocialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSocialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSocial');
    }
}