<?php

/**
 * UserContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserContact');
    }
}