Gallery:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
      unique: true
  columns:
    title:
      type : string(255)
    description:
      type : string(255)
Photos:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
      unique: true
  columns:
    title:
      type : string(255)
    picpath:
      type : string(255)
    gallery_id:
      type : bigint
    is_default:     { type: boolean, default: false }
  relations:
    Gallery:
      local: gallery_id
      onDelete: CASCADE
Address:
  actAs: [Geographical]
  columns:
    route:
      type: string(255)
    city:
      type: string(100)
    province:
      type: string(100)
    region:
      type: string(100)
    country:
      type:  string(100)
    postal_code:
      type:  string(10)
    latitude:
      type: decimal(18)
      scale: 2
    longitude:
      type: decimal(18)
      scale: 2
Company:
  actAs:
    Timestampable:
    Taggable:
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(100)
      notnull: true
      unique: true
    slogan:
      type: string(255)
    description:
      type: clob
    vat:
      type: string(20)
    fc:
      type: string(20)
    iban:
      type: string(20)
    address_id: bigint
    is_customer:
      type: boolean
    gallery_id:
      type : bigint
  relations:
    Gallery:
      local: gallery_id
    Address:
      local: address_id
      foreign: id
      foreignAlias: CompanyAddress
Agent:
  columns:
    name:
      type: string(50)
    surname:
      type: string(50)
    vat:
      type: string(20)
    cf:
      type: string(20)
    iban:
      type: string(20)
    sf_guard_user_id: bigint
    address_id: bigint
  relations:
    Address:
      local: address_id
      foreign: id
      foreignAlias: CompanyAddress
    User:
      class: sfGuardUser
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_profile
CompanyAgent:
  actAs:
    Timestampable:
  columns:
    company_id:
      type: bigint
      primary: true
    agent_id:
      type: bigint
      primary: true
  relations:
    Company:  { onDelete: CASCADE, local: company_id, foreign: id }
    Agent: { onDelete: CASCADE, local: agent_id, foreign: id }
Category:
  actAs:
    Sluggable:
      fields: [name]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    name: string(255)
Product:
  actAs:
   Blameable:
   Taggable:
   Sluggable:
     fields: [name]
   SoftDelete:
     versionColumn: version
     className: %CLASS%Version
     auditLog: true
  columns:
    code: string(50)
    name: string(255)
    description: clob
    quantity: bigint
    price:
      type: decimal(5)
      scale: 2
      default: 0
    offer_price:
      type: decimal(5)
      scale: 2
      default: 0
    offer_end_date: datetime
    category_id: bigint
    company_id: bigint
    gallery_id:
      type : bigint
  relations:
    Gallery:
      local: gallery_id
    Category:
      local: category_id
      foreign: id
      foreignAlias: product_category
    Company:
      local: company_id
      foreign: id
      foreignAlias: company_product
OrderStatus:
  columns:
    name: string(100)
ProductOrder:
  actAs:
    Blameable:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
    SoftDelete:
  columns:
    number: string(100)
    purchase_date: date
    agent_id: bigint
    customer_id: bigint
    company_id: bigint
    status_order_id: bigint
  relations:
    Agent:
      local: agent_id
      foreign: id
      foreignAlias: agent_order
    OrderStatus:
      local: status_order_id
      foreign: id
      foreignAlias: status_order
DiscountType:
  columns:
    name: string(100)
OrderDetail:
  actAs:
    Blameable:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
    SoftDelete:
  columns:
    order_id:
      type: bigint
      primary: true
    product_id:
      type: bigint
      primary: true
    quantity: integer
    discount:
      type: decimal(5)
      scale: 2
      default: 0
    company_id: bigint
    agent_id: bigint
    discount_type_id:  bigint
    note: string(255)
  relations:
    Company:  { local: company_id, foreign: id }
    Agent: { local: agent_id, foreign: id }
    DiscountType: { local: discount_type_id, foreign: id }
Contact:
  columns:
    name:
      type: string(100)
Social:
  columns:
    name:
      type: string(100)
UserContact:
  columns:
    sf_guard_user_id:
      type: bigint
      primary: true
    contact_id:
      type: bigint
      primary: true
    value: string(255)
  relations:
    User:
      class: sfGuardUser
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_contact
    Contact:
      local: contact_id
      foreign: id
      foreignAlias: contact_user
UserSocial:
  columns:
    sf_guard_user_id:
      type: bigint
      primary: true
    social_id:
      type: bigint
      primary: true
    value: string(255)
  relations:
    User:
      class: sfGuardUser
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_contact
    Social:
      local: social_id
      foreign: id
      foreignAlias: social_user
CompanyContact:
  columns:
    company_id:
      type: bigint
      primary: true
    contact_id:
      type: bigint
      primary: true
    value: string(255)
  relations:
    Company:
      local: company_id
      foreign: id
      foreignAlias: company_contact
    Contact:
      local: contact_id
      foreign: id
      foreignAlias: contact_company
CompanySocial:
  columns:
    company_id:
      type: bigint
      primary: true
    social_id:
      type: bigint
      primary: true
    value: string(255)
  relations:
    Company:
      local: company_id
      foreign: id
      foreignAlias: company_contact
    Social:
      local: social_id
      foreign: id
      foreignAlias: social_company
Configuration:
  columns:
    name:
      type: string(100)
    value:
      type: string(255)